# s3:
#    enabled: true
#    endpoint: "my_s3_endpoint.com" 
#    backet: "my_s3_backet_name"
#    credential_name: "my_name_windows_credential_s3"
#    part_size: 15728640 # 15MB в байтах
#
# yandex_disk:
#   enabled: true
#   credential_name: "my_name_windows_credential_yd"
#   path_to_backup: "Backup1C"
#
#  local_directory_path: "D:/files/"
#
#  directory_struct:
#    - prefix_file: "prefix_1"
#      cloud_dir: "prefix_1"
#    - prefix_file: "prefix_2"
#      cloud_dir: "prefix_2"
#    - prefix_file: "prefix_3"
#      cloud_dir: "prefix_3"

s3:
  enabled: true
  endpoint: "ru-msk-dr3-1.store.cloud.mts.ru"
  backet: "backup1c"
  credential_name: "cloud_backuper"
  part_size: 15728640 # 15MB

yandex_disk:
  enabled: true
  credential_name: "yd_backuper"
  path_to_backup: "Backup1C"
  
local_directory_path: "E:/BackUp/sql"

directory_struct:
  - prefix_file: "HRM_backup"
    cloud_dir: "HRM"
  - prefix_file: "Accounting_backup"
    cloud_dir: "Accounting"
  - prefix_file: "unf_30_backup"
    cloud_dir: "unf_30"
